# Generated by Django 3.2.16 on 2022-12-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdnest', '0003_auto_20221228_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='closest_position',
        ),
        migrations.RemoveField(
            model_name='person',
            name='data',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='first.last@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='+123456789', max_length=100),
        ),
    ]
